branches:
  - name: prod
  - name: stg
    prerelease: true
  - name: dev
    prerelease: true
tagFormat: "${version}" # default is v${version} 
plugins:
  - "@semantic-release/commit-analyzer"
  # - "@semantic-release/github"
